// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Idlgen.Cpp
{
    internal sealed partial class Vsix
    {
        public const string Id = "IdlgenCpp.e65ac391-3a5d-4701-bbf2-e26e9f56de71";
        public const string Name = "Idlgen.Idlgen.Cpp Extension";
        public const string Description = @"Provides support for IDL generation from C++ header using IdlGen.IdlGen.Cpp nuget package.";
        public const string Language = "en-US";
        public const string Version = "0.1.1";
        public const string Author = "Roxk Yiu";
        public const string Tags = "idl, midl, C++, idlgen";
    }
}
