// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Idlgen.Cpp
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CppHeaderSelectedString = "832db40a-438e-49e3-a300-cc7ede3ee208";
        public static Guid CppHeaderSelected = new Guid(CppHeaderSelectedString);

        public const string IdlgenCppString = "6a532ba2-8723-4c20-bb58-c3c92006188e";
        public static Guid IdlgenCpp = new Guid(IdlgenCppString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FileMenu = 0x0002;
        public const int CppGenerateIDL = 0x0101;
    }
}