namespace SampleApp
{
enum Category
{
Literature = 0,
Science = 1,
};
}
namespace SampleApp
{
[flags]
enum Permission
{
Camera = 0x00000001,
Microphone = 0x00000002,
};
}
namespace SampleApp
{
struct Point
{
Int64 X;
Int64 Y;
};
}
namespace SampleApp
{
delegate void BlankPageEventHandler(SampleApp.BlankPage sender, UInt64 e);
}
namespace SampleApp
{
runtimeclass BlankPage : Windows.UI.Xaml.Controls.Page
{
BlankPage();
SampleApp.Category Category{get;};
SampleApp.Permission Permission{get;};
void AssignHandler(SampleApp.BlankPageEventHandler handler);
protected Boolean ProtectedGetter();
void ClickHandler(Object sender, Windows.UI.Xaml.RoutedEventArgs args);
Int32 MyProperty();
void MyProperty(Int32 value);
SampleApp.Point GetPoint();
}
}
