name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - run: ./scripts/clone-llvm
      - run: ./scripts/download-clang-lib
      - run: ./scripts/ci
  build-nuget:
    runs-on: windows-2022
    needs: ["test"]
    if: startsWith(github.ref, 'refs/tags/v')
    env:
      VERSION: 0.1.21
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - run: |
          ./scripts/clone-llvm
          ./scripts/download-clang-lib
          ./scripts/build-nuget -version $env:VERSION
          ./scripts/publish-nuget -version $env:VERSION
  build-extension:
    runs-on: windows-2022
    needs: ["test"]
    if: startsWith(github.ref, 'refs/tags/idlgencpp-vs2022-v')
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - run: ./scripts/build-extension -config Release
      - uses: cezarypiatek/VsixPublisherAction@0.2
        with:
          extension-file: './extension/Idlgen.Cpp-Vs-2022/Idlgen.Cpp/bin/Release/Idlgen.Cpp.vsix'
          publish-manifest-file: './extension/Idlgen.Cpp-Vs-2022/vs-publish.json'
          personal-access-code: ${{ secrets.VS_MARKETPLACE_API_KEY }}
